name = "stat-wars-api"
main = "src/index.ts"
compatibility_date = "2025-08-15"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"            # first migration tag
new_classes = ["GameRoom"]