name = "stat-wars-server"
main = "src/index.ts"
compatibility_date = "2024-12-01" # or latest

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]