account_id = "7e82a961d611b4da3302754b79904896"
name = "stat-wars-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[dev]
ip = "127.0.0.1"
port = 8787